eureka:
  instance:
    hostname: localhost # The hostname to register with Eureka
  client:
    registerWithEureka: false # Indicates whether this instance should register itself with the discovery server.
    fetchRegistry: false # Indicates whether this client should fetch eureka registry information from eureka server.
server:
    port: 8761
